package com.hcl.ex;

public class Ex2 {
/**
* The main entry point.
* @param args has the args
*/
	
  public static void main(String[] args) { 
/**
* The main entry point.
*/
try { 
System.out.println("A");
throw new NullPointerException(); //it will throw ths exception bcz it is inside the try block
} 
catch(ArithmeticException e) { 
System.out.println(e);
} 
catch(NullPointerException e) { 
		//System.out.println("error");
throw new NumberFormatException();
} 
catch (NumberFormatException e) { 
		System.out.println("rethrown error");
	} 
 } 
} 
